### ISSUE TITLE
After Authorize events are not firing

### ISSUE THREAD

**Issue by Peterculazh** [Thream/socketio-jwt#12]
## Steps To Reproduce

1. Server Side
```
this.io = new Server(this.di.server.listener);
this.io.use(
    authorize({
        secret: "test"
    })
);
this.io
    .on('connection', socket => {
        console.log("authenticated", socket.decodedToken); // No any messages in console
 });
```
2. Client Side
```
io({
    extraHeaders: { Authorization: `Bearer ${Cookie.get('jwt')}}` }
});
```
3.
```
    "socket.io": "^3.0.5",
    "socket.io-client": "^3.0.5"
```

## The current behavior

No any actions happens after middleware of socket.io using this package. 
I mean `on.("connection")` never fired after adding `use(authorize(...)`. Once I'm removing `use(authorize(...))` sockets are connects fine.

**Comment by Divlo** [comment]
This might happen for many cause, we need more information to investigate :
- Is `Cookie.get('jwt')` is defined client side and it contains the JWT signed server side with the secret `"test"` ?
- What is the output of this code client side :
```js
const socket = io({ extraHeaders: { Authorization: `Bearer ${Cookie.get('jwt')}` } })
socket.on('connect_error', (error) => { 
  console.log(error)
})
```

Maybe there are others edge cases, thanks your report, hopefully, we can get it working! @Peterculazh

**Comment by Peterculazh** [comment]
Sorry, for long no answer, I'll get to that in few days to test code that you supply and will type results there.
As for first two questions:
1. Yeah, secret for JWT just simple text `test`
2. To be honest, just signed jwt without looking onto algorithms, so I think it uses default algorithm, but I'll look letr as I mentioned and will provide to you any info about that

**Comment by Divlo** [comment]
Right, also someone mentioned that the options for the `extraHeaders` client-side is maybe wrong as it is in the current `README` so you could also test with his way.
See: #14

**Comment by Peterculazh** [comment]
Well, I run everything again and didn't faced issue with connecting and it's run great for now without any error. (Placed event emmiting on error as you said). 
So I think it's fine to close that issue.
