### ISSUE TITLE
Client side usage example has errors.

### ISSUE THREAD

**Issue by abgault** [Thream/socketio-jwt#14]
### Documentation :

- [ ] Is Missing
- [x] Is Confusing
- [x] Has Typo errors
- [ ] Not Sure?

### Proposal

Using socket.io-client@3.0.5, the example given for adding the Authorization header does not work.

This:
```
const socket = io('http://localhost:9000', {
  extraHeaders: { Authorization: `Bearer ${yourJWT}` }
})
```

Should be:
```
const socket = io('http://localhost:9000', {
            transportOptions: {
                polling: {
                    extraHeaders: {
                        Authorization: `Bearer ${yourJWT}`,
                    },
                },
            },
        });
```

**Comment by Divlo** [comment]
Hey @abgault! 👋
Thanks for your report!
In the tests with `jest`, I'm using `socket.io-client` and it seems like it's working fine as it is in the current `README` but you're right in the official docs from `socket.io-client` they are using `transportOptions` : [link to the documentation](https://github.com/socketio/socket.io-website/blob/master/source/docs/v3/client-api.md#with-extraheaders).

So yes I'm definitely +1 for that, if you could open a PR for that, it would be awesome, thanks! :+1:

**Comment by Divlo** [comment]
@abgault 
I checked again the docs, and the typings for the engine options seems to be correct as it is currently in the `README` so I'm closing this issue as it is now, feel free to reopen if you think it's wrong, thanks!

https://github.com/socketio/socket.io-client/blob/be81a2ce6fb429a70a008e71945cc5bf9261e77a/lib/manager.ts#L183
