### ISSUE TITLE
Types for Connect Error

### ISSUE THREAD

**Issue by dickensaround** [Thream/socketio-jwt#328]
Apologies if this is poorly worded as I'm just getting started with Typescript. 

I'm trying to implement types as instructed in the Socket.io [documentation](https://socket.io/docs/v4/typescript/), and my IDE is throwing an error on the connect_error event for this package.

This bit:

```node
this.socket.on('connect_error', (err) => {
      if (err.data && err.data.type === 'UnauthorizedError') {
        console.log('User token has expired');
      }
    });
```

Results in:
`Property 'data' does not exist on type 'Error'.ts(2339)`

Is there a best practice way of fixing this? Thanks.

**Comment by Divlo** [comment]
Hey! :wave: @dickensaround 
Thanks for your report!

It is indeed a thing that we need to improve.
You can set `err` to `any` like that:
```ts
this.socket.on('connect_error', (err: any) => {
  if (err.data && err.data.type === 'UnauthorizedError') {
    console.log('User token has expired');
  }
});
```

Thanks to this commit https://github.com/Thream/socketio-jwt/commit/098475d64c5fe3d4ded1b1ea6cb1296f77011a7f, this has been improved with better types, so now we can do something like that:
```ts
if (isUnauthorizedError(error)) {
  console.log('User token has expired')
}
```

README.md has been updated, see: https://github.com/Thream/socketio-jwt#client-side.
