### ISSUE TITLE
[Question] How can I use this plugin with 'require'?

### ISSUE THREAD

**Issue by alex-yplabs** [Thream/socketio-jwt#343]
### Question
Hey!

Can you help me please regarding using @thream/socketio-jwt with 'require'? Currently, I am getting error code: 'ERR_REQUIRE_ESM'. I can't use the module type (import) since my entire nodejs server is built with require. 

Thanks!

**Comment by meyvan** [comment]
> ### Question
> Hey!
> 
> Can you help me please regarding using @thream/socketio-jwt with 'require'? Currently, I am getting error code: 'ERR_REQUIRE_ESM'. I can't use the module type (import) since my entire nodejs server is built with require.
> 
> Thanks!

Here is what I tried:
Got some good info from : https://stackoverflow.com/questions/57169793/error-err-require-esm-how-to-use-es6-modules-in-node-12/70231903#70231903

Then followed their repo: https://github.com/jason-henriksen/typescript-with-esm-no-babel-boilerplate

Which worked partially and gave me error in another dependency

Then I tried installing this one: https://github.com/scristobal/auth0-socketio which gave me the exact same error as before

So I threw everythign away and copy pasted: https://github.com/scristobal/auth0-socketio/blob/main/src/auth0-socketio.ts

into my own code. And it works like a charm

**Comment by Divlo** [comment]
Hello, thanks for your report!

This package is pure ESM. Please [read this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
It will not going back to CommonJS again.
However, I agree that it could be more explicit in the README that it is a pure ESM package, feel free to open a PR to precise that. :smile:
