### ISSUE TITLE
[Feature] Add support for WebSocket as transport

### ISSUE THREAD

**Issue by Divlo** [Thream/socketio-jwt#37]
## Description

We can use `socket.io` with mutiple transports type, as it is described in the `socket.io` documentation : <https://socket.io/docs/v3/client-initialization/#transports>

Currently, we only support `polling` transport.
If you use the `websocket` transport, you can't pass the token in the `extraHeaders` : <https://socket.io/docs/v3/client-initialization/#extraHeaders>, so we don't support it.

## Describe the solution you'd like

Maybe we could retrieve the token thanks to query string instead of the `extraHeaders` : <https://socket.io/docs/v3/client-initialization/#query>

**Comment by EdNutting** [comment]
Unless I have mixed up packages somewhere...

Socket.io has [an `auth` field where you can pass a token](https://socket.io/docs/v3/middlewares/#Sending-credentials). The code change to support web sockets (including from the web browser) is pretty trivial and would then comply with the socket.io way of doing things:

```ts
export function authorize(options: AuthorizeOptions): SocketIOMiddleware {
    const { secret, algorithms = ["HS256"] } = options;
    return async (socket, next) => {
        const encodedToken = socket.handshake.auth.token;
        if (!encodedToken || typeof encodedToken !== "string") {
...
```

i.e. remove the header code and replace it with just `const encodedToken = socket.handshake.auth.token;`.

The client code is then trivial:

```ts
const mySocket = io(url, {
    transports: ["websocket"],
    auth: {
        token,
    },
} as any);
```
(Although socket.io-client hasn't added the `auth` field to their TS types yet, hence the forced type `any`).

**Comment by Divlo** [comment]
Thanks for your help! @EdNutting 
I agree that the `auth` option is better to pass the token since it is how `socket.io` handle authentication in the documentation, I didn't know this option.
Also, I don't have any issues with TypeScript, I don't need to set `as any` to use this option, I checked in the source code, and it seems like they have the types for this option, so no problem for that.
See: https://github.com/socketio/socket.io-client/blob/311c5d14c37a960f331bb9eed7e6f5a7ecd12f49/lib/socket.ts#L8-L13

I just released `@thream/socketio-jwt@2.0.0` with this new change! :smile: 
However, the support for `websocket` transport with this `auth` option is not explicitly stated in the documentation.
Could someone could test the new version of `@thream/socketio-jwt@2.0.0` and tell us if it is indeed working with `websocket` transport ? Thanks.

I would love if @skipper09, could test the new version and test if it is working with `websocket` transport, so we can close this issue.

**Comment by skipper09** [comment]
Hey Divlo! I don't have the capacity right now to test such changes. I did know with the original socketio-jwt package, the query option did not work. I had to use extraHeaders. I was actually able to get the original package to work so I used that. Thanks!

**Comment by SayakMukhopadhyay** [comment]
> Could someone could test the new version of `@thream/socketio-jwt@2.0.0` and tell us if it is indeed working with `websocket` transport ? Thanks.

I have just tested this using Firecamp and this *seems* to work for both Polling only and Websocket only transports. Seems cause I have tested by checking whether the client object in the `connection` event had the decoded token or not and it had so I believe it works.

**Comment by ekrotenko** [comment]
Original library supports authentication in websocket using "noQsMethod".
Cannot understand why you removed it, especially if this fork kind of "official".
