### ISSUE TITLE
Add encoded and decoded token to socket type

### ISSUE THREAD

**Issue by sovcik** [Thream/socketio-jwt#4]
### Type of Improvement :

- [ ] Files and Folders Structure
- [ ] Performance
- [x] Refactoring code
- [ ] Tests
- [ ] Not Sure?

### Proposal
Extend socket property type so its properties are visible for TypeScript.

1. define new TS interface for socket e.g. 
```
interface ExtendedSocket extends Socket {
   encodedToken?: string;
   decodedToken?: any;
}
```
2.  make property socket in SocketIOMiddleware of type ExtendedSocket
```
type SocketIOMiddleware = (
  socket: ExtendedSocket,
  next: (err?: ExtendedError) => void
) => void
```

**Comment by Divlo** [comment]
Sure, I like this improvement, do you mind open a pull request ? :+1: 
Thanks! @sovcik

**Comment by sovcik** [comment]
Will do. Sorry, was lazy reating it yesterday :-)
